#!/usr/bin/env bash
# Writing a Bash script that displays numbers from 1 to 20 and:

# To display 4 and then bad luck from China for the 4th loop iteration
# To display 9 and then bad luck from Japan for the 9th loop iteration
# To display 17 and then bad luck from Italy for the 17th loop iteration
# Use the while loop (for and until are forbidden)
# Use the case statement

i=1

while [ $i -le 20 ]
do
  echo "$i"
  case $i in
    "4") echo "bad luck from China";;
    "9") echo "bad luck from Japan";;
    "17") echo "bad luck from Italy";;
  esac
  (( i++ ))
done
