#!/usr/bin/env bash
# Display the content of the current directory in list format
# Display only the part of the name after the first dash

mylist=$(ls)

for i in $mylist; do
  echo "$i" | cut -d '-' -f2
done
